# Generated by Django 5.2.1 on 2025-05-19 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Job_Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Experience', models.CharField(blank=True, max_length=50, null=True)),
                ('Qualifications', models.TextField(blank=True, null=True)),
                ('Salary_Range', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('Work_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Job_Posting_Date', models.DateField(blank=True, null=True)),
                ('Preference', models.CharField(blank=True, max_length=50, null=True)),
                ('Job_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Role', models.CharField(blank=True, max_length=200, null=True)),
                ('Company', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('simplified_role', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('Min_Exp', models.IntegerField(blank=True, null=True)),
                ('Max_Exp', models.IntegerField(blank=True, null=True)),
                ('Min_Salary', models.FloatField(blank=True, null=True)),
                ('Max_Salary', models.FloatField(blank=True, null=True)),
                ('Sector', models.CharField(blank=True, max_length=200, null=True)),
                ('Responsibility_List', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobid', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibility', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Benefits', models.TextField(blank=True, null=True)),
                ('benefit', models.TextField(blank=True, null=True)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='visualiztion.job')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='visualiztion.job')),
            ],
        ),
    ]
